#!/bin/sh
while read -r field value size; do
    if [ -n "${size}" ]; then
        value="$((value/1024))"
        size="MB"
    fi
    printf "%s %s %s\n" "${field}" "${value}" "${size}"
done </proc/meminfo

